"""Atualiza checklist com novos campos

Revision ID: 1d132d79c21b
Revises: 
Create Date: 2025-06-13 22:52:50.067554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d132d79c21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cracha_ibge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recibo_entrega', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questionario_mrs_impresso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questionario_map_impresso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('carta_oficial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questionario_mrs_digital', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questionario_map_digital', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('manual_pnsb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guia_site_externo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('card_contato', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('audio_explicativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('planejamento_rota', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agenda_confirmada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('apresentacao_ibge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_objetivo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_estrutura', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_data_referencia', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_prestador', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_servicos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_site_externo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explicacao_pdf_editavel', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('validacao_prestadores', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registro_contatos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_informante', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('devolucao_materiais', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registro_followup', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('combinacao_entrega', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('combinacao_acompanhamento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_finais', sa.Boolean(), nullable=True))

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checklist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'checklists', ['checklist_id'], ['id'])

    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('observacoes_finais')
        batch_op.drop_column('combinacao_acompanhamento')
        batch_op.drop_column('combinacao_entrega')
        batch_op.drop_column('registro_followup')
        batch_op.drop_column('devolucao_materiais')
        batch_op.drop_column('assinatura_informante')
        batch_op.drop_column('registro_contatos')
        batch_op.drop_column('validacao_prestadores')
        batch_op.drop_column('explicacao_pdf_editavel')
        batch_op.drop_column('explicacao_site_externo')
        batch_op.drop_column('explicacao_servicos')
        batch_op.drop_column('explicacao_prestador')
        batch_op.drop_column('explicacao_data_referencia')
        batch_op.drop_column('explicacao_estrutura')
        batch_op.drop_column('explicacao_objetivo')
        batch_op.drop_column('apresentacao_ibge')
        batch_op.drop_column('agenda_confirmada')
        batch_op.drop_column('planejamento_rota')
        batch_op.drop_column('audio_explicativo')
        batch_op.drop_column('card_contato')
        batch_op.drop_column('guia_site_externo')
        batch_op.drop_column('manual_pnsb')
        batch_op.drop_column('questionario_map_digital')
        batch_op.drop_column('questionario_mrs_digital')
        batch_op.drop_column('carta_oficial')
        batch_op.drop_column('questionario_map_impresso')
        batch_op.drop_column('questionario_mrs_impresso')
        batch_op.drop_column('recibo_entrega')
        batch_op.drop_column('cracha_ibge')

    # ### end Alembic commands ###
