"""Ajuste final modelo contatos

Revision ID: 45b8c4200dbc
Revises: c7649ef95e42
Create Date: 2025-06-15 14:13:28.055398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b8c4200dbc'
down_revision = 'c7649ef95e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.drop_column('fonte_local')
        batch_op.drop_column('fonte_responsavel')
        batch_op.drop_column('fonte_endereco')
        batch_op.drop_column('fonte_contato')
        batch_op.drop_column('fonte_horario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fonte_horario', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('fonte_contato', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('fonte_endereco', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('fonte_responsavel', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('fonte_local', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
