"""Adiciona campo tipo_informante na tabela visitas

Revision ID: 62eb23985fbe
Revises: 45b8c4200dbc
Create Date: 2025-06-15 17:12:08.727893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eb23985fbe'
down_revision = '45b8c4200dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_informante', sa.String(length=30), nullable=True, server_default='prefeitura'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('tipo_informante')

    # ### end Alembic commands ###
