"""Atualiza contatos para campos de IA

Revision ID: c7649ef95e42
Revises: 
Create Date: 2025-06-15 13:50:12.183054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7649ef95e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_chatgpt', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('local_gemini', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('local_grok', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('local_mais_provavel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsavel_chatgpt', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsavel_gemini', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsavel_grok', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsavel_mais_provavel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('endereco_chatgpt', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('endereco_gemini', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('endereco_grok', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('endereco_mais_provavel', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('contato_chatgpt', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contato_gemini', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contato_grok', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contato_mais_provavel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('horario_chatgpt', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('horario_gemini', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('horario_grok', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('horario_mais_provavel', sa.String(length=200), nullable=True))
        batch_op.drop_column('responsavel')
        batch_op.drop_column('local')
        batch_op.drop_column('horario')
        batch_op.drop_column('endereco')
        batch_op.drop_column('contato')

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pesquisa', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('tipo_pesquisa')

    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('local', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('responsavel', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('horario_mais_provavel')
        batch_op.drop_column('horario_grok')
        batch_op.drop_column('horario_gemini')
        batch_op.drop_column('horario_chatgpt')
        batch_op.drop_column('contato_mais_provavel')
        batch_op.drop_column('contato_grok')
        batch_op.drop_column('contato_gemini')
        batch_op.drop_column('contato_chatgpt')
        batch_op.drop_column('endereco_mais_provavel')
        batch_op.drop_column('endereco_grok')
        batch_op.drop_column('endereco_gemini')
        batch_op.drop_column('endereco_chatgpt')
        batch_op.drop_column('responsavel_mais_provavel')
        batch_op.drop_column('responsavel_grok')
        batch_op.drop_column('responsavel_gemini')
        batch_op.drop_column('responsavel_chatgpt')
        batch_op.drop_column('local_mais_provavel')
        batch_op.drop_column('local_grok')
        batch_op.drop_column('local_gemini')
        batch_op.drop_column('local_chatgpt')

    # ### end Alembic commands ###
